---
- name: Hardening Bastion server
  hosts: bastion
  become: yes
  roles:
    - os_hardening
  
- name: OS Hardening Application servers
  hosts: app_servers
  become: yes
  roles:
    - os_hardening

- name: Deploy Nginx
  hosts: bastion
  become: yes
  roles:
    - nginx_deploy

- name: Deploy FastAPI
  hosts: app_servers
  become: yes
  roles:
    - app_deploy