---
# 1. Package Installation
- name: Install security-essential and python packages
  ansible.builtin.dnf:
    name: 
      - python3-pip
      - python3-devel
    state: present
    update_cache: yes

# 4. Direct Code Sync (Creates directory automatically)
- name: Sync data with rsync (fixed for timeouts)
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/"
    dest: /home/ec2-user/class25-26-project2/
    use_ssh_args: yes  # Forces rsync to use your Ansible SSH settings
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o ConnectTimeout=60"

- name: Ensure .venv has correct permissions or is removed
  ansible.builtin.file:
    path: "/home/ec2-user/class25-26-project2/.venv"
    state: absent
  become: yes  # Run as root to ensure we can delete it regardless of owner

# 5. Virtual Environment & Dependencies
- name: Setup .venv and install requirements
  ansible.builtin.pip:
    requirements: "/home/ec2-user/class25-26-project2/requirements.txt"
    virtualenv: "/home/ec2-user/class25-26-project2/.venv"
    virtualenv_command: python3 -m venv
  become: yes
  become_user: ec2-user

# 6. Service & Nginx Deployment (Templates)
- name: Deploy FastAPI systemd service
  ansible.builtin.template:
    src: project.service.j2
    dest: /etc/systemd/system/fastapi.service
    mode: '0644'
  notify: Restart FastAPI

# 7. Final Service Activation
- name: Ensure FastAPI and Nginx are running
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: [fastapi]