---
# 1. Package Installation (OFFLINE)
- name: Install security packages from local RPM folder
  ansible.builtin.shell: |
    dnf install -y --disablerepo=* /tmp/offline-packages/*.rpm
  register: hardening_pkg_install
  # This prevents dnf from looking at the internet
  become: yes

# 2. Security Hardening: Firewall
- name: Ensure firewalld is running
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: Allow SSH, HTTP, and HTTPS in Public Zone
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    zone: public
  loop: [ssh, http, https]
  notify: reload_firewall

- name: Allow ALB Health Checks via Rich Rule (High Priority)
  ansible.posix.firewalld:
    rich_rule: 'rule family="ipv4" source address="{{ target_vpc_cidr }}" port port="80" protocol="tcp" accept'
    permanent: yes
    state: enabled
    service: http
    immediate: yes
  notify: reload_firewall

- name: Ensure Port 8000 is open for Nginx-to-FastAPI Proxy
  ansible.posix.firewalld:
    port: 8000/tcp
    permanent: yes
    state: enabled
    immediate: yes
  notify: reload_firewall


# 3. Security Hardening: Time Sync
- name: Configure AWS Time Sync
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    line: "server 169.254.169.123 prefer iburst"
    state: present
  notify: restart_chrony

# 4. Security Hardening: Fail2Ban
# 4. Security Hardening: Fail2Ban
- name: Create local fail2ban config with VPC whitelist
  ansible.builtin.copy:
    content: |
      [DEFAULT]
      ignorself = true
      ignoreip = 127.0.0.1/8 {{ target_vpc_cidr }}
      # Ensure fail2ban uses systemd journal on modern OS
      backend = systemd

      [sshd]
      enabled = true
    dest: /etc/fail2ban/jail.local
    force: yes

- name: Ensure Fail2Ban is running
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes