[bastion]
bastion_node ansible_host={{ BASTION_PUBLIC_IP }}

[app_servers]
app_node ansible_host={{ APP_PRIVATE_IP }}

[all:vars]
ansible_user=ec2-user
# We use the alias 'bastion_node' in the ProxyCommand to keep it clean
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q ec2-user@{{ BASTION_PUBLIC_IP }}"'
ansible_ssh_private_key_file=~/.ssh/id_rsa