[bastion]
bastion ansible_host="{{ BASTION_IP }}"

[app_servers]
app_node ansible_host="{{ APP_IP }}"

[app_servers:vars]
# Use the shell environment variable syntax $BASTION_IP 
# which matches what you've exported in your GitHub Action
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ec2-user@{{ hostvars["bastion"]["ansible_host"] }}'

[all:vars]
ansible_user=ec2-user