---
- name: Install security-essential packages
  ansible.builtin.apt:
    name: [ufw, fail2ban, chrony, unattended-upgrades]
    state: present
    update_cache: yes

- name: Configure UFW Firewall
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: ['22', '80', '443']

- name: Enable Firewall
  community.general.ufw:
    state: enabled
    policy: deny

- name: Ensure AWS Time Sync is configured (CIS/AWS Best Practice)
  ansible.builtin.lineinfile:
    path: /etc/chrony/chrony.conf
    line: "server 169.254.169.123 prefer iburst"
    state: present
  notify: restart_chrony

- name: Ensure automatic security updates are enabled
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

# 1. Install Nginx
- name: Ensure Nginx is installed
  ansible.builtin.apt:
    name: nginx
    state: present

# 2. Copy FastAPI Systemd Service File
- name: Copy FastAPI systemd service file
  ansible.builtin.template:
    src: /templates/project.service.j2
    dest: /etc/systemd/system/project.service
    mode: '0644'
  notify: Restart FastAPI

# 3. Configure Nginx as Reverse Proxy
- name: Copy Nginx configuration
  ansible.builtin.template:
    src: nginx_fastapi.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: Reload Nginx

# 6. Ensure services are started and enabled
- name: Ensure FastAPI and Nginx are running
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: [fastapi, nginx]