---
# 1. Package Installation
- name: Install RPMs strictly offline
  ansible.builtin.shell: |
    dnf install -y --disablerepo=* /tmp/offline-packages/*.rpm
  register: shell_output

- name: Print dnf output
  ansible.builtin.debug:
    var: shell_output.stdout_lines

- name: Deploy Nginx configuration
  ansible.builtin.template:
    src: nginx_fastapi.conf.j2
    dest: /etc/nginx/conf.d/fastapi.conf
    mode: '0644'
  notify: Reload Nginx

- name: Ensure FastAPI and Nginx are running
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: [nginx]